// docker 结构化补全数据。
//
// 数据来源：docs.docker.com CLI 参考常用项（docker ps/exec/logs/run/compose 等），
// 格式借鉴 fig 完成规范的 command/option/args 三层思路。
// 裁剪原则：两层子命令树（docker container/image/network/volume/system/compose）；
// 只保留运维高频 flag；容器名/镜像名等远端动态值一律 `dynamic` 提示。
import type { SpecCommand } from "../spec";

export const dockerSpec: SpecCommand = {
  name: "docker",
  description: "Container engine CLI",
  flags: [{ name: "context", description: "Target a specific context", arg: "name" }, { name: "host", short: "H", description: "Daemon socket to connect to", arg: "socket" }],
  subcommands: [
    {
      name: "ps",
      description: "List containers",
      flags: [
        { name: "all", short: "a", description: "Show all containers (default shows running)" },
        { name: "quiet", short: "q", description: "Only display container IDs" },
        { name: "latest", short: "l", description: "Show the latest created container" },
        { name: "size", short: "s", description: "Display total file sizes" },
        { name: "filter", short: "f", description: "Filter output (status=running etc)", arg: "filter" },
        { name: "format", description: "Format output (Go template)", arg: "template" },
        { name: "no-trunc", description: "Do not truncate output" },
      ],
    },
    {
      name: "exec",
      description: "Run a command in a running container",
      flags: [
        { name: "interactive", short: "i", description: "Keep STDIN open" },
        { name: "tty", short: "t", description: "Allocate a pseudo-TTY" },
        { name: "detach", short: "d", description: "Run in the background" },
        { name: "env", short: "e", description: "Set environment variable", arg: "VAR=value" },
        { name: "user", short: "u", description: "Username or UID", arg: "user" },
        { name: "workdir", short: "w", description: "Working directory inside the container", arg: "dir" },
        { name: "privileged", description: "Give extended privileges" },
      ],
      positional: { name: "container", dynamic: true },
    },
    {
      name: "logs",
      description: "Fetch container logs",
      flags: [
        { name: "follow", short: "f", description: "Follow log output" },
        { name: "tail", description: "Number of lines from the end", arg: "lines" },
        { name: "since", description: "Logs since a timestamp", arg: "timestamp" },
        { name: "until", description: "Logs before a timestamp", arg: "timestamp" },
        { name: "timestamps", short: "t", description: "Show timestamps" },
        { name: "details", description: "Show extra details" },
      ],
      positional: { name: "container", dynamic: true },
    },
    {
      name: "run",
      description: "Create and start a container",
      flags: [
        { name: "detach", short: "d", description: "Run in the background" },
        { name: "interactive", short: "i", description: "Keep STDIN open" },
        { name: "tty", short: "t", description: "Allocate a pseudo-TTY" },
        { name: "name", description: "Container name", arg: "name" },
        { name: "publish", short: "p", description: "Publish a port", arg: "host:container" },
        { name: "volume", short: "v", description: "Bind mount a volume", arg: "src:dst" },
        { name: "env", short: "e", description: "Set environment variable", arg: "VAR=value" },
        { name: "rm", description: "Remove the container on exit" },
        { name: "restart", description: "Restart policy", arg: "policy", values: ["no", "on-failure", "always", "unless-stopped"] },
        { name: "network", description: "Connect to a network", arg: "network" },
        { name: "memory", short: "m", description: "Memory limit", arg: "bytes" },
        { name: "entrypoint", description: "Overwrite the entrypoint", arg: "cmd" },
      ],
      positional: { name: "image", dynamic: true },
    },
    { name: "images", description: "List images", flags: [{ name: "all", short: "a", description: "Show all images" }, { name: "quiet", short: "q", description: "Only image IDs" }, { name: "digests", description: "Show digests" }, { name: "filter", short: "f", description: "Filter output", arg: "filter" }] },
    { name: "pull", description: "Pull an image from a registry", flags: [{ name: "all-tags", short: "a", description: "Pull all tagged images" }, { name: "platform", description: "Target platform", arg: "platform" }, { name: "quiet", short: "q", description: "Suppress verbose output" }], positional: { name: "image", dynamic: true } },
    { name: "push", description: "Push an image to a registry", flags: [{ name: "all-tags", short: "a", description: "Push all tagged images" }], positional: { name: "image", dynamic: true } },
    { name: "build", description: "Build an image from a Dockerfile", flags: [{ name: "tag", short: "t", description: "Name and tag the image", arg: "name:tag" }, { name: "file", short: "f", description: "Dockerfile path", arg: "path" }, { name: "no-cache", description: "Do not use cache" }, { name: "pull", description: "Always pull newer base images" }, { name: "build-arg", description: "Build-time variable", arg: "VAR=value" }], positional: { name: "path", dynamic: true } },
    { name: "cp", description: "Copy files between container and filesystem", flags: [{ name: "archive", short: "a", description: "Archive mode (copy all uid/gid)" }, { name: "follow-link", short: "L", description: "Always follow symbolic links" }], positional: { name: "src:dst", dynamic: true } },
    { name: "inspect", description: "Return low-level information on objects", flags: [{ name: "size", short: "s", description: "Display total file sizes" }, { name: "format", description: "Format with a Go template", arg: "template" }], positional: { name: "object", dynamic: true } },
    { name: "stats", description: "Live container resource usage", flags: [{ name: "all", short: "a", description: "Include stopped containers" }, { name: "no-stream", description: "One snapshot and exit" }, { name: "format", description: "Go template format", arg: "template" }] },
    { name: "top", description: "Running processes of a container", positional: { name: "container", dynamic: true } },
    { name: "kill", description: "Signal a container", flags: [{ name: "signal", short: "s", description: "Signal to send", arg: "signal" }], positional: { name: "container", dynamic: true } },
    { name: "stop", description: "Stop running containers", flags: [{ name: "time", short: "t", description: "Seconds to wait before killing", arg: "seconds" }], positional: { name: "container", dynamic: true } },
    { name: "start", description: "Start stopped containers", flags: [{ name: "attach", short: "a", description: "Attach STDOUT/STDERR" }, { name: "interactive", short: "i", description: "Attach STDIN" }], positional: { name: "container", dynamic: true } },
    { name: "restart", description: "Restart containers", flags: [{ name: "time", short: "t", description: "Seconds to wait before killing", arg: "seconds" }], positional: { name: "container", dynamic: true } },
    { name: "rm", description: "Remove containers", flags: [{ name: "force", short: "f", description: "Force removal of running containers" }, { name: "volumes", short: "v", description: "Remove anonymous volumes" }, { name: "link", short: "l", description: "Remove the specified link" }], positional: { name: "container", dynamic: true } },
    { name: "rmi", description: "Remove images", flags: [{ name: "force", short: "f", description: "Force removal" }, { name: "no-prune", description: "Do not delete untagged parents" }], positional: { name: "image", dynamic: true } },
    { name: "info", description: "Display system-wide information", flags: [{ name: "format", description: "Go template format", arg: "template" }] },
    { name: "version", description: "Show docker version information", flags: [{ name: "format", description: "Go template format", arg: "template" }] },
    {
      name: "container",
      description: "Manage containers",
      subcommands: [
        { name: "ls", description: "List containers (alias of docker ps)", flags: [{ name: "all", short: "a", description: "Show all containers" }, { name: "quiet", short: "q", description: "Only container IDs" }] },
        { name: "run", description: "Create and run a container" },
        { name: "exec", description: "Run a command in a running container" },
        { name: "logs", description: "Fetch container logs", flags: [{ name: "follow", short: "f", description: "Follow log output" }, { name: "tail", description: "Lines from the end", arg: "lines" }] },
        { name: "stop", description: "Stop containers" },
        { name: "start", description: "Start containers" },
        { name: "restart", description: "Restart containers" },
        { name: "rm", description: "Remove containers", flags: [{ name: "force", short: "f", description: "Force removal" }] },
        { name: "inspect", description: "Inspect container details" },
        { name: "prune", description: "Remove all stopped containers" },
      ],
    },
    {
      name: "image",
      description: "Manage images",
      subcommands: [
        { name: "ls", description: "List images", flags: [{ name: "all", short: "a", description: "Show all images" }, { name: "quiet", short: "q", description: "Only image IDs" }] },
        { name: "pull", description: "Pull an image" },
        { name: "push", description: "Push an image" },
        { name: "build", description: "Build an image", flags: [{ name: "tag", short: "t", description: "Name and tag", arg: "name:tag" }] },
        { name: "rm", description: "Remove images", flags: [{ name: "force", short: "f", description: "Force removal" }] },
        { name: "prune", description: "Remove unused images", flags: [{ name: "all", short: "a", description: "Remove all unused images" }] },
        { name: "inspect", description: "Inspect image details" },
      ],
    },
    {
      name: "network",
      description: "Manage networks",
      subcommands: [
        { name: "ls", description: "List networks" },
        { name: "create", description: "Create a network", flags: [{ name: "driver", short: "d", description: "Network driver", arg: "driver" }, { name: "subnet", description: "Subnet in CIDR", arg: "cidr" }] },
        { name: "rm", description: "Remove networks" },
        { name: "inspect", description: "Inspect a network" },
        { name: "prune", description: "Remove all unused networks" },
      ],
    },
    {
      name: "volume",
      description: "Manage volumes",
      subcommands: [
        { name: "ls", description: "List volumes" },
        { name: "create", description: "Create a volume" },
        { name: "rm", description: "Remove volumes" },
        { name: "inspect", description: "Inspect a volume" },
        { name: "prune", description: "Remove all unused volumes" },
      ],
    },
    {
      name: "system",
      description: "Manage docker system state",
      subcommands: [
        { name: "df", description: "Show docker disk usage", flags: [{ name: "verbose", short: "v", description: "Detailed usage" }] },
        { name: "prune", description: "Remove unused data", flags: [{ name: "all", short: "a", description: "Remove unused images too" }, { name: "volumes", description: "Prune volumes" }, { name: "force", short: "f", description: "Do not prompt" }] },
        { name: "info", description: "System information" },
      ],
    },
    {
      name: "compose",
      description: "Multi-container applications",
      subcommands: [
        { name: "up", description: "Create and start containers", flags: [{ name: "detach", short: "d", description: "Run in the background" }, { name: "build", description: "Build images before starting" }, { name: "force-recreate", description: "Recreate containers" }] },
        { name: "down", description: "Stop and remove containers", flags: [{ name: "volumes", short: "v", description: "Remove named volumes" }, { name: "remove-orphans", description: "Remove containers for services not defined" }] },
        { name: "ps", description: "List services", flags: [{ name: "all", short: "a", description: "Include stopped" }] },
        { name: "logs", description: "Service logs", flags: [{ name: "follow", short: "f", description: "Follow output" }, { name: "tail", description: "Lines from the end", arg: "lines" }] },
        { name: "build", description: "Build or rebuild services" },
        { name: "pull", description: "Pull service images" },
        { name: "restart", description: "Restart services" },
        { name: "exec", description: "Execute a command in a service container" },
        { name: "config", description: "Validate and view compose file", flags: [{ name: "quiet", short: "q", description: "Only validate" }] },
      ],
    },
  ],
};
