// git 结构化补全数据（命令 → 子命令 → flag）。
//
// 数据来源：git 官方文档（git-scm.com/docs）与 git-scm 手册页常用项，格式
// 借鉴 fig 完成规范的 command/option/args 三层思路。
// 裁剪原则：只保留运维高频子命令与 flag；每个子命令 3-8 个最常用 flag；
// 分支/文件等远端动态值一律 `dynamic` 提示，不做本地枚举；不带 AI/运行时依赖。
import type { SpecCommand } from "../spec";

export const gitSpec: SpecCommand = {
  name: "git",
  description: "Distributed version control system",
  flags: [{ name: "version", description: "Print the git suite version" }, { name: "help", description: "Show help for a command" }, { name: "no-pager", description: "Do not pipe output into a pager" }],
  subcommands: [
    {
      name: "status",
      description: "Show the working tree status",
      flags: [
        { name: "short", short: "s", description: "Give the output in the short-format" },
        { name: "branch", short: "b", description: "Show branch and tracking info in short format" },
        { name: "porcelain", description: "Stable machine-readable output" },
        { name: "ignored", description: "Show ignored files too" },
        { name: "untracked-files", short: "u", description: "Show untracked files", arg: "mode", values: ["all", "normal", "no"] },
      ],
    },
    {
      name: "log",
      description: "Show commit history",
      flags: [
        { name: "oneline", description: "One commit per line" },
        { name: "graph", description: "Draw a text-based commit graph" },
        { name: "all", description: "Pretend all refs are listed on the command line" },
        { name: "follow", description: "Follow renames for a single file" },
        { name: "pretty", description: "Pretty-print output", arg: "format", values: ["oneline", "short", "medium", "full", "raw", "format"] },
        { name: "since", description: "Commits more recent than a date", arg: "date" },
        { name: "until", description: "Commits older than a date", arg: "date" },
        { name: "stat", description: "Show diffstat per commit" },
        { name: "patch", short: "p", description: "Show the patch introduced by each commit" },
        { name: "max-count", short: "n", description: "Limit number of commits", arg: "count" },
      ],
      positional: { name: "path", dynamic: true },
    },
    {
      name: "diff",
      description: "Show changes between commits, working tree, etc",
      flags: [
        { name: "staged", description: "Show changes staged for the next commit" },
        { name: "cached", description: "Alias of --staged" },
        { name: "stat", description: "Generate a diffstat" },
        { name: "shortstat", description: "Only the last line of the diffstat" },
        { name: "name-only", description: "Show only names of changed files" },
        { name: "color-words", description: "Word-diff highlighted in color" },
        { name: "ignore-all-space", short: "w", description: "Ignore whitespace when comparing lines" },
      ],
      positional: { name: "commit/path", dynamic: true },
    },
    {
      name: "add",
      description: "Stage file contents for the next commit",
      flags: [
        { name: "all", short: "A", description: "Stage all known files plus new ones" },
        { name: "update", short: "u", description: "Stage only already-tracked files" },
        { name: "patch", short: "p", description: "Interactively choose hunks" },
        { name: "dry-run", short: "n", description: "Do not actually add files" },
        { name: "force", short: "f", description: "Allow adding otherwise-ignored files" },
        { name: "interactive", short: "i", description: "Interactive mode" },
      ],
      positional: { name: "pathspec", dynamic: true },
    },
    {
      name: "commit",
      description: "Record changes to the repository",
      flags: [
        { name: "message", short: "m", description: "Use the given message", arg: "msg" },
        { name: "all", short: "a", description: "Stage all tracked files before committing" },
        { name: "amend", description: "Replace the tip of the current branch" },
        { name: "no-edit", description: "Amend without editing the message" },
        { name: "allow-empty", description: "Create a commit with no changes" },
        { name: "signoff", short: "s", description: "Add Signed-off-by trailer" },
        { name: "author", description: "Override commit author", arg: "author" },
        { name: "dry-run", description: "Show what would be committed" },
      ],
    },
    {
      name: "checkout",
      description: "Switch branches or restore working tree files",
      flags: [
        { name: "branch", short: "b", description: "Create and switch to a new branch", arg: "name" },
        { name: "force-branch", short: "B", description: "Create or reset and switch to a branch", arg: "name" },
        { name: "orphan", description: "New unborn branch", arg: "name" },
        { name: "track", short: "t", description: "Set upstream for the new branch" },
        { name: "detach", description: "Detach HEAD at the named commit" },
        { name: "ours", description: "Conflicts: check out our version" },
        { name: "theirs", description: "Conflicts: check out their version" },
        { name: "force", short: "f", description: "Throw away local changes" },
        { name: "patch", short: "p", description: "Interactively select hunks" },
      ],
      positional: { name: "branch", dynamic: true },
    },
    {
      name: "switch",
      description: "Switch branches (modern alternative to checkout)",
      flags: [
        { name: "create", short: "c", description: "Create and switch to a new branch", arg: "name" },
        { name: "detach", short: "d", description: "Switch to a commit for inspection" },
        { name: "discard-changes", description: "Discard local changes" },
        { name: "force-create", short: "C", description: "Create or reset a branch", arg: "name" },
      ],
      positional: { name: "branch", dynamic: true },
    },
    {
      name: "branch",
      description: "List, create or delete branches",
      flags: [
        { name: "all", short: "a", description: "List remote-tracking and local branches" },
        { name: "remotes", short: "r", description: "List remote-tracking branches" },
        { name: "delete", short: "d", description: "Delete a fully merged branch" },
        { name: "force-delete", short: "D", description: "Delete regardless of merge state" },
        { name: "move", short: "m", description: "Rename a branch", arg: "newname" },
        { name: "contains", description: "Only branches containing the commit", arg: "commit" },
        { name: "show-current", description: "Print the name of the current branch" },
      ],
      positional: { name: "branchname", dynamic: true },
    },
    {
      name: "merge",
      description: "Join two development histories together",
      flags: [
        { name: "no-ff", description: "Create a merge commit even for fast-forward" },
        { name: "ff-only", description: "Refuse to merge unless fast-forward" },
        { name: "squash", description: "Squash changes into one commit on top" },
        { name: "abort", description: "Abort the current conflict resolution" },
        { name: "continue", description: "Conclude the current conflict resolution" },
        { name: "message", short: "m", description: "Merge commit message", arg: "msg" },
      ],
      positional: { name: "branch", dynamic: true },
    },
    {
      name: "rebase",
      description: "Reapply commits on top of another base tip",
      flags: [
        { name: "interactive", short: "i", description: "Interactive rebase" },
        { name: "continue", description: "Restart the rebasing process after resolving" },
        { name: "abort", description: "Abort and restore the original branch" },
        { name: "skip", description: "Restart, skipping the current commit" },
        { name: "autosquash", description: "Automatically squash fixup! commits" },
        { name: "onto", description: "Start rebase onto a new base", arg: "newbase" },
      ],
      positional: { name: "upstream", dynamic: true },
    },
    {
      name: "pull",
      description: "Fetch from and integrate with another repository",
      flags: [
        { name: "rebase", description: "Rebase local commits on top of fetched", arg: "strategy" },
        { name: "ff-only", description: "Abort if not fast-forward" },
        { name: "no-rebase", description: "Merge instead of rebase" },
        { name: "tags", description: "Fetch all tags as well" },
        { name: "prune", description: "Remove remote-tracking refs that no longer exist" },
        { name: "autostash", description: "Stash local changes before, pop after" },
      ],
      positional: { name: "remote/branch", dynamic: true },
    },
    {
      name: "push",
      description: "Update remote refs along with associated objects",
      flags: [
        { name: "force", short: "f", description: "Overwrite remote refs" },
        { name: "force-with-lease", description: "Overwrite only if remote is as expected" },
        { name: "set-upstream", short: "u", description: "Set upstream for every pushed branch" },
        { name: "delete", short: "d", description: "Delete remote refs" },
        { name: "tags", description: "Push all refs under refs/tags" },
        { name: "dry-run", short: "n", description: "Do everything except actually send" },
        { name: "all", description: "Push all branches" },
      ],
      positional: { name: "remote/branch", dynamic: true },
    },
    {
      name: "fetch",
      description: "Download objects and refs from another repository",
      flags: [
        { name: "all", description: "Fetch all remotes" },
        { name: "prune", short: "p", description: "Remove stale remote-tracking refs" },
        { name: "tags", short: "t", description: "Fetch all tags" },
        { name: "force", short: "f", description: "Overwrite local refs" },
        { name: "depth", description: "Shallow fetch limited to N commits", arg: "depth" },
        { name: "dry-run", description: "Show what would be fetched" },
      ],
      positional: { name: "remote", dynamic: true },
    },
    {
      name: "stash",
      description: "Stash the changes in a dirty working directory",
      subcommands: [
        { name: "push", description: "Save your local modifications to a new stash", flags: [{ name: "message", short: "m", description: "Stash description", arg: "msg" }, { name: "include-untracked", short: "u", description: "Include untracked files" }, { name: "keep-index", short: "k", description: "Keep staged changes intact" }] },
        { name: "pop", description: "Apply a stash and drop it", flags: [{ name: "index", description: "Try to reinstate staged changes" }] },
        { name: "list", description: "List the stashes you have" },
        { name: "apply", description: "Apply a stash without dropping it" },
        { name: "drop", description: "Remove a single stash entry" },
        { name: "clear", description: "Remove all stash entries" },
      ],
    },
    {
      name: "cherry-pick",
      description: "Apply the changes introduced by existing commits",
      flags: [
        { name: "continue", description: "Continue after resolving conflicts" },
        { name: "abort", description: "Cancel the operation" },
        { name: "no-commit", short: "n", description: "Apply changes without committing" },
        { name: "edit", short: "e", description: "Edit the commit message" },
        { name: "signoff", short: "s", description: "Add Signed-off-by trailer" },
      ],
      positional: { name: "commit", dynamic: true },
    },
    {
      name: "revert",
      description: "Revert existing commits by creating inverse commits",
      flags: [
        { name: "no-edit", description: "Do not edit the commit message" },
        { name: "no-commit", short: "n", description: "Revert without committing" },
        { name: "abort", description: "Cancel the operation" },
        { name: "continue", description: "Continue after resolving conflicts" },
      ],
      positional: { name: "commit", dynamic: true },
    },
    {
      name: "reset",
      description: "Reset current HEAD to a specified state",
      flags: [
        { name: "soft", description: "Keep index and working tree" },
        { name: "mixed", description: "Reset index, keep working tree (default)" },
        { name: "hard", description: "Reset index and working tree" },
        { name: "patch", short: "p", description: "Interactively select hunks" },
      ],
      positional: { name: "commit/path", dynamic: true },
    },
    {
      name: "restore",
      description: "Restore working tree files",
      flags: [
        { name: "staged", description: "Restore the index contents" },
        { name: "worktree", short: "W", description: "Restore the working tree (default)" },
        { name: "source", short: "s", description: "Restore from a given tree", arg: "tree" },
        { name: "staged-worktree", short: "SW", description: "Restore both index and working tree" },
      ],
      positional: { name: "pathspec", dynamic: true },
    },
    {
      name: "remote",
      description: "Manage tracked repositories",
      subcommands: [
        { name: "add", description: "Add a remote", flags: [{ name: "track", short: "t", description: "Track only the given branch", arg: "branch" }] },
        { name: "remove", description: "Remove a remote (rm)" },
        { name: "rename", description: "Rename a remote" },
        { name: "set-url", description: "Change the URL of a remote" },
        { name: "show", description: "Give information about a remote" },
        { name: "prune", description: "Delete stale remote-tracking branches" },
        { name: "update", description: "Fetch updates for remotes" },
      ],
      flags: [{ name: "verbose", short: "v", description: "Show remote URLs" }],
    },
    {
      name: "tag",
      description: "Create, list, verify or delete tags",
      flags: [
        { name: "list", short: "l", description: "List tags matching a pattern" },
        { name: "delete", short: "d", description: "Delete tags", arg: "tag" },
        { name: "annotate", short: "a", description: "Make an unsigned, annotated tag", arg: "tag" },
        { name: "message", short: "m", description: "Tag message", arg: "msg" },
        { name: "force", short: "f", description: "Replace an existing tag" },
      ],
    },
    { name: "clone", description: "Clone a repository into a new directory", flags: [{ name: "depth", description: "Shallow clone", arg: "depth" }, { name: "branch", short: "b", description: "Checkout a specific branch", arg: "name" }, { name: "bare", description: "Create a bare repository" }, { name: "recurse-submodules", description: "Clone and init submodules" }], positional: { name: "repository", dynamic: true } },
    { name: "init", description: "Create an empty git repository", flags: [{ name: "bare", description: "Create a bare repository" }, { name: "initial-branch", short: "b", description: "Initial branch name", arg: "name" }] },
    { name: "show", description: "Show objects and refs", flags: [{ name: "stat", description: "Show diffstat" }, { name: "name-only", description: "Show changed file names" }], positional: { name: "object", dynamic: true } },
    { name: "blame", description: "Show last modification per line", flags: [{ name: "line-porcelain", description: "Full porcelain per line" }, { name: "show-stats", description: "Include summary statistics" }], positional: { name: "file", dynamic: true } },
  ],
};
