// pnpm 结构化补全数据（包管理器三件套之一，见 npm.ts 头注释的来源与裁剪原则）。
import type { SpecCommand } from "../spec";

export const pnpmSpec: SpecCommand = {
  name: "pnpm",
  description: "Fast, disk-efficient package manager",
  flags: [{ name: "version", short: "v", description: "Print pnpm version" }, { name: "dir", short: "C", description: "Run as if started in this path", arg: "path" }],
  subcommands: [
    {
      name: "install",
      description: "Install dependencies (alias: i)",
      flags: [
        { name: "prod", short: "P", description: "Production dependencies only" },
        { name: "dev", short: "D", description: "Development dependencies only" },
        { name: "frozen-lockfile", description: "Fail when the lockfile needs updating" },
        { name: "no-frozen-lockfile", description: "Allow lockfile updates" },
        { name: "offline", description: "Registry-free install from the store" },
        { name: "prefer-offline", description: "Use cached data when fresh" },
        { name: "force", short: "f", description: "Re-resolve and reinstall" },
        { name: "ignore-scripts", description: "Skip lifecycle scripts" },
        { name: "filter", description: "Workspace filter", arg: "selector" },
      ],
    },
    {
      name: "add",
      description: "Install a package and save it",
      flags: [
        { name: "save-dev", short: "D", description: "Save to devDependencies" },
        { name: "save-prod", short: "P", description: "Save to dependencies" },
        { name: "save-optional", short: "O", description: "Save to optionalDependencies" },
        { name: "save-exact", short: "E", description: "Pin the exact version" },
        { name: "global", short: "g", description: "Install globally" },
        { name: "save-peer", description: "Save to peerDependencies" },
      ],
      positional: { name: "package", dynamic: true },
    },
    {
      name: "remove",
      description: "Remove packages (alias: rm)",
      flags: [{ name: "global", short: "g", description: "Remove globally" }, { name: "save-dev", short: "D", description: "Remove from devDependencies" }],
      positional: { name: "package", dynamic: true },
    },
    { name: "update", description: "Update packages (alias: up)", flags: [{ name: "latest", description: "Ignore the version range" }, { name: "global", short: "g", description: "Update global packages" }, { name: "interactive", description: "Choose outdated packages interactively" }], positional: { name: "package", dynamic: true } },
    { name: "run", description: "Run a package.json script", flags: [{ name: "filter", description: "Workspace filter", arg: "selector" }, { name: "parallel", description: "Run across workspace packages concurrently" }], positional: { name: "script", dynamic: true } },
    { name: "test", description: "Run the package test script" },
    { name: "exec", description: "Execute a shell command in the project", flags: [{ name: "filter", description: "Workspace filter", arg: "selector" }, { name: "parallel", description: "Run concurrently" }], positional: { name: "command", dynamic: true } },
    { name: "dlx", description: "Fetch and run a package in a one-off environment", positional: { name: "package", dynamic: true } },
    { name: "create", description: "Scaffold a project from a create-* initializer", positional: { name: "template", dynamic: true } },
    { name: "list", description: "List installed packages (alias: ls)", flags: [{ name: "depth", description: "Tree depth", arg: "level" }, { name: "global", short: "g", description: "Global packages" }, { name: "json", description: "JSON output" }] },
    { name: "outdated", description: "List outdated packages", flags: [{ name: "format", description: "Output format", arg: "format", values: ["list", "table"] }, { name: "long", description: "Extended info" }] },
    { name: "why", description: "Show why a package is installed", positional: { name: "package", dynamic: true } },
    { name: "audit", description: "Security audit of dependencies", flags: [{ name: "fix", description: "Apply compatible fixes" }, { name: "json", description: "JSON output" }] },
    { name: "store", description: "Manage the content-addressable store", subcommands: [{ name: "status", description: "Check for modified packages" }, { name: "add", description: "Add a package to the store", positional: { name: "package", dynamic: true } }, { name: "prune", description: "Remove unreferenced packages" }, { name: "path", description: "Print the store path" }] },
    { name: "prune", description: "Remove extraneous packages" },
    { name: "link", description: "Link a local package", positional: { name: "path", dynamic: true } },
    { name: "unlink", description: "Remove links created by pnpm link" },
    { name: "publish", description: "Publish a package", flags: [{ name: "access", description: "Visibility for scoped packages", arg: "level", values: ["public", "restricted"] }, { name: "tag", description: "Registry dist-tag", arg: "tag" }, { name: "otp", description: "One-time password", arg: "code" }] },
    { name: "pack", description: "Create a tarball from a package", flags: [{ name: "pack-destination", description: "Output directory", arg: "dir" }] },
    { name: "rebuild", description: "Run a package's build scripts", positional: { name: "package", dynamic: true } },
    { name: "import", description: "Generate a pnpm-lock.yaml from another package manager" },
    { name: "init", description: "Create a package.json", flags: [{ name: "workspace", short: "W", description: "Initialize a workspace" }] },
    { name: "env", description: "Manage Node.js versions", subcommands: [{ name: "use", description: "Install and use a Node version", positional: { name: "version", dynamic: true } }, { name: "add", description: "Install a Node version" }, { name: "remove", description: "Remove a Node version" }, { name: "ls", description: "List Node versions" }] },
    { name: "dedupe", description: "Deduplicate dependencies in node_modules" },
  ],
};
